### ISSUE TITLE
MATLAB R2015b

### ISSUE THREAD

**Issue by ilariaparel** [u0078867/ulema-ul-analyzer#27]
Hello!

I am trying to use ULEMA with the new version of MATLAB, R2015b.
I just want to let you know that the code doesn't work, becasue I think Matlab changed some "rules".

Error in CalculateFunctionalJointCenters, line 131.
Matlab doesn't permit to change an element of a cellarray in a struct anymore.

Could you confirm it?
Thank you!

**Comment by u0078867** [comment]
Yes, I confirm it, a colleague of mine had the same issue with the same MATLAB version. 
I will check it asap.

Thanks for the feedback

**Comment by u0078867** [comment]
I plan to fix this on Wednesday 22nd June. ;)

**Comment by u0078867** [comment]
Fixed in version 1.1.8
